name: Build app
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
  NEXT_PUBLIC_SANITY_API_WRITE_TOKEN: ${{ secrets.NEXT_PUBLIC_SANITY_API_WRITE_TOKEN }}
  SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }}
  NEXT_PUBLIC_SANITY_DATASET: ${{ vars.NEXT_PUBLIC_SANITY_DATASET }}
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ vars.NEXT_PUBLIC_SANITY_PROJECT_ID }}

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Set BRANCH_NAME
        id: set_branch
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "BASE_URL=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BASE_URL=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm eslint .

      - name: Build app
        run: pnpm build
